<?php

namespace AppBundle\Repository;

/**
 * JokeCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JokeCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
