<?php

namespace AppBundle\Repository;

/**
 * JokeLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JokeLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
