<?php

namespace AppBundle\Repository;

/**
 * JokeShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JokeShareRepository extends \Doctrine\ORM\EntityRepository
{
}
