<?php

namespace AppBundle\Repository;

/**
 * ReportedJokeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportedJokeRepository extends \Doctrine\ORM\EntityRepository
{
}
